name: Create and Push QEMU image

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v2

    - name: Install qemu
      run: sudo apt-get update && sudo apt-get install qemu-system -y
    
    - name: Setup packer
      uses: hashicorp/setup-packer@main
    
    - name: build QEMU image
      run: |
        packer init
        packer build qemu-image.pkr.hcl