name: Create and Push QEMU image

on:
  push: {}

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PACKER_LOG: "1"

    steps:
    - name: checkout code
      uses: actions/checkout@v4

    - name: Install qemu and 
      run: |
        sudo apt-get update 
        sudo apt-get install -y qemu-system
        sudo apt-get install -y xorriso
        sudo chmod 666 /dev/kvm
    
    - name: Setup packer
      uses: hashicorp/setup-packer@main
    
    - name: build QEMU image
      run: |
        packer init qemu-image.pkr.hcl
        packer build\
          --var source_headless=true \
          --var accelerator=kvm \
          qemu-image.pkr.hcl
        

    - name: upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: qemu-image
        path: output
